language: c

group: stable

os: linux

script:
  - make re

notifications:
  email: false

addons:
  apt:
    packages:
      - libncurses5-dev
      - libncursesw5-dev

before_script:
  - apt update
  - apt install libncurses5-dev libncursesw5-dev

after_success:
  - bash <(curl -s https://codecov.io/bash)
