language: c

group: stable

os: linux

sudo: required

dist: precise

script:
  - make re

notifications:
  email: false

before_install:
  - sudo apt update
  - sudo apt install libncurses5-dev libncursesw5-dev

after_success:
  - bash <(curl -s https://codecov.io/bash)
